export default {
  me: {
    name: 'Per Jansson',
    title: 'Fullstack Web Developer',
    contacts: [
      {
        medium: 'Medium',
        url: 'https://medium.com/@perjansson',
      },
      {
        medium: 'GitHub',
        url: 'https://github.com/perjansson',
      },
      {
        medium: 'LinkedIn',
        url: 'https://www.linkedin.com/in/pichdude',
      },
      {
        medium: 'Stack Overflow',
        url: 'https://stackoverflow.com/users/274426/per-jansson',
      },
      {
        medium: 'Twitter',
        url: 'https://www.twitter.com/per_jansson',
      },
      {
        medium: 'Instagram',
        url: 'https://instagram.com/per_jansson',
      },
      {
        medium: 'Facebook',
        url: 'https://www.facebook.com/pichdude',
      },
      {
        medium: 'Email',
        url: 'mailto:per.r.jansson@gmail.com',
      },
    ],
    short:
      "Hi, I'm Per, a curious software developer with a passion to build great applications and help others do the same.",
    long:
      'I’m a <span class="focus">curious software developer</span> with a passion to build great stuff and support others to do the same. My core skills are in <span class="focus">full-stack web development</span> and, although I’m no stranger to backend, I’ve always been drawn to the <span class="focus">frontend</span> side. I like the things that are visual and that a user interacts with and I have many years of experience in how to build systems and applications that are a <span class="focus">good mix of quality, robustness and ease of use</span>. I really enjoy working with <span class="focus">Node, React, React-Native and JavaScript</span> in general, but I also have done a lot of Java previously together with both Android och iOS development. I addition to that I also like the architectural part of how a solid frontend is created together with making the <span class="focus">Developer Experience</span> really good for the current team so it’s a joy to work with.<br/><br/>I love helping teams become <span class="focus">more efficient</span> by supporting the establishment of great practices for <span class="focus">agile product development</span> methods with a focus on teamwork and organizing the work. I have experience in <span class="focus">team leadership and coaching</span> activities within the agile way of delivering software and I strive to be a person who gets others to grow, the team to achieve more, and to <span class="focus">maximize the value for the end-user</span> and the client.',
  },
  projects: [
    {
      id: 21,
      title: 'Panasonic Avionics Corporation',
      description:
        'Platform to enable airplane passengers to attain wireless internet connectivity.',
      me:
        'Software developer helping Panasonic developing new services to enable airplane passengers to attain wireless internet connectivity. Daily work consists of implementing new features and at the same time gradually modernizing the technical solution as well as helping the development team build a solution that will be a solid platform for the future.',
      role: 'Frontend developer',
      date: '2020-',
      asset: 'pac',
      tags: [
        'javascript',
        'react',
        'redux',
        'redux-saga',
        'material-ui',
        'storybook',
        'jest',
        'react-testing-library',
        'cypress',
        'cucumber',
        'node',
        'npm',
        'lerna',
        'gitlab',
        'docker',
      ],
    },
    {
      id: 20,
      title: 'HBO GO app',
      description:
        'HBO GO client in US for TV platforms: Samsung Orsay, TiVo set-top box and Hotels (LG and Enseo devices). A web application using HTML, CSS, and TypeScript. Frameworks and libraries used are React, Redux, Styled Components and Ramda. It is built using Grunt and Browserify.',
      me:
        'Software developer of the HBO GO app for different platforms and devices. Daily work consists of both developing new features in a shiny new codebase but also maintaining and solving tricky problems in a legacy codebase. Fun and challenging!',
      role: 'Frontend developer',
      date: '2018-2019',
      asset: 'hbogo',
      tags: [
        'typescript',
        'react',
        'redux',
        'styled-components',
        'storybook',
        'jest',
        'enzyme',
        'node',
        'npm',
        'git',
        'jenkins',
        'vs code',
      ],
    },
    {
      id: 19,
      title: 'Unibet Frontend for Kindred Group',
      description:
        'Several different betting websites built using web technologies and using configuration of a headless CMS to create the final experience for the client.',
      me:
        'Frontend developer in a team responsible for Unibet, Storspelare, Bingo.com and Bohemia Casino. Development of mostly new features build with the latest technologies but also maintaining legacy code. Trying daily to contribute to team becoming more efficient both in programming but also in team work and good development practices.',
      role: 'Frontend developer',
      date: '2017-2018',
      asset: 'unibet',
      tags: [
        'javascript',
        'react',
        'redux',
        'reselect',
        'styled-components',
        'jest',
        'enzyme',
        'storybook',
        'storyshots',
        'webpack',
        'babel',
        'html',
        'sass',
        'node',
        'yarn',
        'cypress',
        'codemods',
        'jscodeshift',
        'git',
        'jenkins',
        'vs code',
      ],
    },
    {
      id: 18,
      title: 'Insourcing Matchmaking Tool for EY',
      description:
        'A web application that act as a matchmaking tool to find the best candidate of insourced consultants and employees for a given client and project. Also a back-office module for administrators and consultants to manage their skills, CVs, personal video, details etc.',
      me:
        "Responsible for building the full experience, ie. the client, a responsive web app that's both fast and intuitive to use, and the server with business logic, a nodejs app with mongodb as persistence.",
      role: 'Fullstack developer',
      date: '2016-2018',
      asset: 'matchmaking-tool',
      tags: [
        'javascript',
        'angular',
        'ngxs',
        'react',
        'graphql',
        'apollo',
        'sass',
        'animate.css',
        'express',
        'jwt',
        'passport',
        'lodash',
        'node',
        'npm',
        'webpack',
        'typescript',
        'mongodb',
        'heroku',
        'aws s3',
        'mlab',
        'papertrail',
        'pushover',
      ],
    },
    {
      id: 17,
      title: 'New Admin web for Leadenhancer',
      description:
        'Web application for back office of company that bridges the gap between known and anonymous web visitors by identifying and segmenting the companies visiting a website, and providing detailed, targetable business attributes in real-time.',
      me:
        'Frontend responsible to build a new admin web to support the needs of the admin users of Leadenhancer. Involves everything from architecture and build and deploy pipeline, REST api design to coding the bits and pieces that are a modern web application.',
      role: 'Frontend developer',
      date: '2016-2017',
      asset: 'le',
      tags: [
        'javascript',
        'angular',
        'node',
        'npm',
        'sass',
        'eslint',
        'prettier',
        'webpack',
      ],
    },
    {
      id: 16,
      title: 'Digitalization and Advisory Cockpit Tool for Nordea Bank',
      description:
        "Advisory Cockpit Tool to be used by advisors and help digitize an advisor's everyday. The bar was set very high and the application should not only contain a lot of functionality to simplify the days of an advisor, but the end result will also be a great user experience.",
      me:
        'Development and architecture of the frontend and BFF part of the application. Setting up fast and solid development experience and in general building the foundation of an easy to develop and maintain system. Daily work with building pages and components together with API design.',
      role: 'Frontend architect & developer',
      date: '2016-2018',
      asset: 'cocpit',
      tags: [
        'javascript',
        'react',
        'redux',
        'reselect',
        'express',
        'node',
        'npm',
        'webpack',
        'babel',
        'lodash',
        'html',
        'material-ui',
        'sass',
        'css modules',
        'standardjs',
        'mocha',
        'chai',
        'sinon',
        'enzyme',
        'faker.js',
        'moment',
        'postman',
        'java',
        'spring',
        'jackson',
        'scrum',
        'tdd',
        'jenkins',
      ],
    },
    {
      id: 15,
      title: 'Mindmend prototype',
      description: 'A prototype for a digital platform for KBT treatment.',
      me:
        'Developer of a responsive web app, everything from Sketch to running in the cloud.',
      role: 'Fullstack developer',
      asset: 'mindmend',
      date: '2017',
      tags: [
        'javascript',
        'html',
        'jquery',
        'materialize',
        'sass',
        'animate.css',
        'express',
        'node',
        'npm',
        'webpack',
        'heroku',
        'agile',
      ],
    },
    {
      id: 14,
      title: 'Nordic portfolio system for Nordea Bank',
      description:
        'A brand new back office solution along with enhancing and introducing an existing portfolio system in the Nordic countries',
      me:
        'Coding frontend architect developing the frontend tier, setting up fast and solid development practices/processes/style guides and build system together with being a happy team player working very close to the end user to guarantee the best result.',
      role: 'Frontend developer',
      asset: 'admin_tool',
      tags: [
        'javascript',
        'angularjs',
        'es2015',
        'node',
        'npm',
        'gulp',
        'bower',
        'jquery',
        'underscore',
        'html',
        'bootstrap',
        'sass',
        'jshint',
        'csslint',
        'htmlhint',
        'karma',
        'protractor',
        'mocha',
        'chai',
        'sinon',
        'java',
        'spring',
        'hibernate',
        'dozer',
        'flying saucer',
        'intellij',
        'git',
        'maven',
        'jenkins',
        'sonarqube',
        'sql server',
        'tdd',
        'ddd',
        'kanban',
        'xp',
      ],
    },
    {
      id: 13,
      title: 'Risk Calculator for Nordea Bank',
      description:
        "A system for calculating risk and return, both based on a customer's current portfolio but also on a better allocated portfolio that will be recommended to the customer.",
      me:
        'Full stack developer of the entire system, although primarily responsible for frontend and API, together with being a happy team player working very close to the end user to guarantee the best result.',
      role: 'Fullstack developer',
      asset: 'risk_calculator',
      tags: [
        'angularjs',
        'html',
        'css',
        'boostrap',
        'karma',
        'protractor',
        'java',
        'spring',
        'hibernate',
        'thymeleaf',
        'flying Saucer',
        'jensoft',
        'dozer',
        'intellij',
        'git',
        'maven',
        'jenkins',
        'sonarqube',
        'sql server',
        'tdd',
        'ddd',
        'scrum',
        'xp',
      ],
    },
    {
      id: 12,
      title: 'Multi portfolio for Nordea Bank',
      description:
        "Portfolio analysis system extended to support structuring a customer's total engagement in different portfolios to be able to twist and turn the customers current assets.",
      me:
        'Development and Scrum Master making sure that the team delivers what the end user expects with good code quality.',
      role: 'Fullstack developer',
      asset: 'multi_portfolio',
      tags: [
        'gwt',
        'java',
        'spring',
        'hibernate',
        'apache camel',
        'dozer',
        'html',
        'css',
        'javascript',
        'intellij',
        'svn',
        'maven',
        'jenkins',
        'sonarqube',
        'sql Server',
        'tdd',
        'ddd',
        'scrum',
        'xp',
      ],
    },
    {
      id: 11,
      title: 'Customized analysis and recommendation for Nordea Bank',
      description:
        "A system for doing customized analysis, optimization and recommendation of customer's current portfolio to be able to recommend a better portfolio that can give a higher return with a lower risk. <a href='https://medium.com/@perjansson/offshoring-from-the-scream-to-friendship-and-success-5b409c30d287' target='_blank' rel='noopener noreferrer'>Blog post about project on Medium</a>.",
      me:
        'Development and architecture of the system. Being UX and front end responsible to make the system easy and fast to use. Be proactive in efforts to get a distributed team between Sweden, Denmark and India to work.',
      role: 'Fullstack developer',
      asset: 'care',
      tags: [
        'gwt',
        'java',
        'spring',
        'hibernate',
        'dozer',
        'html',
        'css',
        'javascript',
        'eclipse',
        'svn',
        'maven',
        'jenkins',
        'sonarqube',
        'sql Server',
        'tdd',
        'ddd',
        'scrum',
        'xp',
        'lean',
      ],
    },
    {
      id: 10,
      title: 'Portfolio for advisors for Nordea Bank',
      description:
        'A web application for advisors to use when doing analysis of a customers holdings, for instance asset allocation, current and previous holdings, transactions, performance and profit and loss. <a href="https://medium.com/@perjansson/how-we-invented-and-introduced-drama-driven-demo-9cc564bc741f" target="_blank" rel="noopener noreferrer">Blog post about project on Medium</a>.',
      me:
        'Development and UX making sure the system makes sense and is easy to use, looks nice and is quick and responsive. Advocate efficient software development practices such as pair programming, TDD, code reviews and brown bag lunches.',
      role: 'Frontend developer',
      asset: 'portfolio',
      tags: [
        'gwt',
        'java',
        'spring',
        'hibernate',
        'dozer',
        'html',
        'css',
        'javascript',
        'eclipse',
        'svn',
        'maven',
        'jenkins',
        'sonarqube',
        'sql Server',
        'tdd',
        'ddd',
        'scrum',
        'xp',
        'lean',
      ],
    },
    {
      id: 9,
      title: 'App on Android for Swedish Pharmacy',
      description:
        'An Android app to view the current pollen level at a given location as well as recommended treatments and view closest pharmacy.',
      me:
        'Develop the Apoteket (swedish pharmacy) application for Android. Took the project from requirements and development to testing and release on Google Play.',
      role: 'Mobile app developer',
      asset: 'pharmacy_app',
      tags: ['android', 'java', 'android studio', 'scrum'],
    },
    {
      id: 8,
      title: 'App on Android for Statoil',
      description:
        'An Android app to view the closest Statoil gas station as well as book trailers, vans etc.',
      me:
        'Develop the Swedish Statoil application for Android. Took the project from requirements and development to testing and release on Google Play.',
      role: 'Mobile app developer',
      asset: 'statoil_app',
      tags: ['android', 'java', 'android studio', 'scrum'],
    },
    {
      id: 7,
      title: 'Planning and sorting system for Swedish Postal Service',
      description:
        'A system to improve the planning and sorting of incoming and outgoing parcels for the Swedish postal service.',
      me:
        'Development with frontend responsibility to make sure the system was intuitive and easy to use. Held workshops with end users about how the interface should look like.',
      role: 'Frontend developer',
      asset: 'postal_service',
      tags: [
        'jsf',
        'richfaces',
        'seam',
        'html',
        'css',
        'javascript',
        'java ee',
        'ejb2',
        'bibernate',
        'sculptur',
        'eclipse',
        'svn',
        'maven',
        'hudson',
        'tdd',
        'ddd',
        'rup',
      ],
    },
    {
      id: 6,
      title: 'Automatic Payments for Länsförsäkringar Bank',
      description:
        'Change several existing bank systems to make sure they worked after a backend system for automatic payments was updated.',
      me:
        'Technical project manager and developer which involved planning and being part of the implementation.',
      role: 'Technical Project Manager',
      asset: 'automatic_payments',
      tags: [
        'jsf',
        'struts',
        'java',
        'spring',
        'hibernate',
        'eclipse',
        'svn',
        'maven',
        'jenkins',
        'xp',
        'scrum',
      ],
    },
    {
      id: 5,
      title: 'Proof Of Concept new Internet bank for SEB (Bank)',
      description:
        'A Proof of concept application to prove that a current internet banking solution could be modified to work for another bank.',
      me:
        'Developer and development lead to show how we worked with planning, analysis, design, development, test and release.',
      role: 'Development lead',
      asset: 'internet_bank_seb_poc',
      tags: [
        'jsf',
        'myfaces',
        'html',
        'css',
        'javascript',
        'java',
        'spring',
        'hibernate',
        'eclipse',
        'svn',
        'maven',
        'xp',
        'rup',
      ],
    },
    {
      id: 4,
      title: 'New Internet Bank for Länsförsäkringar Bank',
      description:
        'Build a new shiny internet bank with new technologies, frameworks and most importantly new functionality. ',
      me:
        'Developer and front end specialist to make sure that the selected technologies played well together when both rebuilding existing functionality but also when adding new.',
      role: 'Frontend developer',
      asset: 'internet_bank_lf',
      tags: [
        'jsf',
        'myfaces',
        'shale',
        'html',
        'css',
        'javascript',
        'java',
        'spring',
        'hibernate',
        'eclipse',
        'svn',
        'maven',
        'apache continuum',
        'xp',
        'rup',
      ],
    },
    {
      id: 3,
      title: 'Change bank application for Länsförsäkringar Bank',
      description:
        'A system to support bank officers help new customers move all of their existing engagement from other banks to Länsförsäkringar Bank.',
      me: 'Developer with front end responsibility.',
      role: 'Frontend developer',
      asset: 'change_bank',
      tags: [
        'jsf',
        'myfaces',
        'shale',
        'html',
        'css',
        'javascript',
        'java',
        'spring',
        'hibernate',
        'eclipse',
        'svn',
        'maven',
        'apache continuum',
        'xp',
        'rup',
      ],
    },
    {
      id: 2,
      title: 'Bank officers secure communication for Länsförsäkringar Bank',
      description:
        'a system to enable a secure communication channel between bank officers and bank customers via the internet bank and an internal bank officer application.',
      me: 'Developer with front end responsibility.',
      role: 'Frontend developer',
      asset: 'secure_communication',
      tags: [
        'struts',
        'html',
        'css',
        'javascript',
        'java ee',
        'ejb 3',
        'hibernate',
        'eclipse',
        'cvs',
        'ant',
        'rup',
      ],
    },
    {
      id: 1,
      title: 'Internet bank for SEB (Bank) in Germany',
      description: 'A new internet bank for SEB in Germany.',
      me: 'Developer with fullstack responsibility.',
      role: 'Fullstack developer',
      asset: 'internet_bank_seb',
      tags: [
        'struts',
        'html',
        'css',
        'javascript',
        'java ee',
        'ejb 3',
        'hibernate',
        'eclipse',
        'cvs',
        'ant',
        'rup',
      ],
    },
  ],
}
